# Generated by Django 4.2.3 on 2023-07-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizzAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('optionA', models.CharField(max_length=100)),
                ('optionB', models.CharField(max_length=100)),
                ('optionC', models.CharField(blank=True, max_length=100)),
                ('optionD', models.CharField(blank=True, max_length=100)),
                ('correctAnswer', models.CharField(max_length=100)),
            ],
        ),
    ]
