# Generated by Django 4.2.3 on 2023-07-29 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_quizzadd'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzadd',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
    ]
